### ISSUE TITLE
playbook change-password throws 403

### ISSUE THREAD

**Issue by karthik137** [we45/ThreatPlaybook#27]
I have  used docker-setup to load the stack.

My docker-compose file -->

```
version: '3'
services:
  nginx:
    image: we45/threatplaybook-nginx:latest
    ports:
      - "80:80"
    depends_on:
      - api
      - frontend
    links:
      - api
      - frontend
  mongo_db:
    image: bitnami/mongodb:latest
    user: root
    environment:
      - MONGODB_USERNAME=threatplaybook
      - MONGODB_PASSWORD=password123
      - MONGODB_DATABASE=threat_playbook
    expose:
      - "27017"
    ports:
      - "27017:27017"
    volumes:
      - ./threatplaybook_db:/bitnami
  api:
    image: we45/threatplaybook-api:latest
    expose:
      - "5042"
    ports:
      - "5042:5042"
    environment:
      - MONGO_HOST=mongo_db
      - MONGO_USER=threatplaybook
      - MONGO_PASS=password123
      - MONGO_PORT=27017
      - MONGO_DB=threat_playbook
      - SUPERUSER_EMAIL=admin@admin.com
      - SUPERUSER_PASS=supersecret
      - JWT_PASS=VGCxqDnhsN6vNQVqmXtrNVVe1AS36ZMQKTq6lYpj0ygHiuWunMOkFi2j17cHSbG-WId9x_yJpeSqy0TTFjs06Q
      - WAIT_HOSTS=mongo_db:27017
    links:
      - mongo_db
    depends_on:
      - mongo_db
    command: sh -c "./wait-for mongo_db:27017 -- /usr/local/bin/python3.6 /threatplaybook/app.py"
  frontend:
    image: we45/threatplaybook-frontend:4.1
    expose:
      - "8080"
    ports:
      - "8080:8080"
    environment:
      - API_URL=http://api:5042
    links:
      - api
    depends_on:
      - api
```

### After executing 'playbook change-password'  api  throws error 

error message -->

```
api_1       | INFO: ('192.168.224.1', 49940) - "POST /change-password HTTP/1.1" 403
```
